// Code generated by "genenum.exe -typesize=uint16 -typename=ResultCode -packagename=resultcode -basedir=enum -vectortype=int"

package resultcode_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/mininet/enum/resultcode"
)

type ResultCodeVector [resultcode.ResultCode_Count]int

func (es ResultCodeVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "ResultCodeVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			resultcode.ResultCode(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *ResultCodeVector) Dec(e resultcode.ResultCode) {
	es[e] -= 1
}
func (es *ResultCodeVector) Inc(e resultcode.ResultCode) {
	es[e] += 1
}
func (es *ResultCodeVector) Add(e resultcode.ResultCode, v int) {
	es[e] += v
}
func (es *ResultCodeVector) SetIfGt(e resultcode.ResultCode, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es ResultCodeVector) Get(e resultcode.ResultCode) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es ResultCodeVector) Iter(fn func(i resultcode.ResultCode, v int) bool) bool {
	for i, v := range es {
		if fn(resultcode.ResultCode(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es ResultCodeVector) VectorAdd(arg ResultCodeVector) ResultCodeVector {
	var rtn ResultCodeVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es ResultCodeVector) VectorSub(arg ResultCodeVector) ResultCodeVector {
	var rtn ResultCodeVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *ResultCodeVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>ResultCode statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return resultcode.ResultCode(i).String()
}

var IndexFn = template.FuncMap{
	"ResultCodeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{ResultCodeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
