// Code generated by "genenum.exe -typesize=uint16 -typename=CommandID -packagename=commandid -basedir=enum -vectortype=int"

package commandid_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/mininet/enum/commandid"
)

type CommandIDVector [commandid.CommandID_Count]int

func (es CommandIDVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "CommandIDVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			commandid.CommandID(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *CommandIDVector) Dec(e commandid.CommandID) {
	es[e] -= 1
}
func (es *CommandIDVector) Inc(e commandid.CommandID) {
	es[e] += 1
}
func (es *CommandIDVector) Add(e commandid.CommandID, v int) {
	es[e] += v
}
func (es *CommandIDVector) SetIfGt(e commandid.CommandID, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es CommandIDVector) Get(e commandid.CommandID) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es CommandIDVector) Iter(fn func(i commandid.CommandID, v int) bool) bool {
	for i, v := range es {
		if fn(commandid.CommandID(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es CommandIDVector) VectorAdd(arg CommandIDVector) CommandIDVector {
	var rtn CommandIDVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es CommandIDVector) VectorSub(arg CommandIDVector) CommandIDVector {
	var rtn CommandIDVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *CommandIDVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>CommandID statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return commandid.CommandID(i).String()
}

var IndexFn = template.FuncMap{
	"CommandIDIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{CommandIDIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
