// Code generated by "genenum.exe -typesize=uint8 -typename=FlowType -packagename=flowtype -basedir=enum -vectortype=int"

package flowtype_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/mininet/example/enum/flowtype"
)

type FlowTypeVector [flowtype.FlowType_Count]int

func (es FlowTypeVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "FlowTypeVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			flowtype.FlowType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *FlowTypeVector) Dec(e flowtype.FlowType) {
	es[e] -= 1
}
func (es *FlowTypeVector) Inc(e flowtype.FlowType) {
	es[e] += 1
}
func (es *FlowTypeVector) Add(e flowtype.FlowType, v int) {
	es[e] += v
}
func (es *FlowTypeVector) SetIfGt(e flowtype.FlowType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es FlowTypeVector) Get(e flowtype.FlowType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es FlowTypeVector) Iter(fn func(i flowtype.FlowType, v int) bool) bool {
	for i, v := range es {
		if fn(flowtype.FlowType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es FlowTypeVector) VectorAdd(arg FlowTypeVector) FlowTypeVector {
	var rtn FlowTypeVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es FlowTypeVector) VectorSub(arg FlowTypeVector) FlowTypeVector {
	var rtn FlowTypeVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *FlowTypeVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>FlowType statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return flowtype.FlowType(i).String()
}

var IndexFn = template.FuncMap{
	"FlowTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{FlowTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
